server:
  servlet:
    context-path: /
  port: 8088
spring:
  datasource:
    url: jdbc:sqlite:/home/lighthouse/lolidate/lolidate.db
    driver-class-name: org.sqlite.JDBC
    username:
env:
    config:
      file_path: /home/lighthouse/lolidate/catcatdm/
      file_list: file.list