server:
  servlet:
    context-path: /
  port: 8088
spring:
  datasource:
    url: jdbc:sqlite:f:\git_pro\lolidate\lolidate.db
    driver-class-name: org.sqlite.JDBC
    username:

env:
    config:
      file_path: f://catcatdm//
      file_list: file.list